src/Entity/Annee.php
<?php

namespace App\Entity;

use App\Repository\AnneeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnneeRepository::class)]
class Annee
{
    #[ORM\Id]
//    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\Column]
    private ?int $ordre = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle_long = null;

    #[ORM\Column]
    private ?bool $opt_alternance = null;

    #[ORM\Column]
    private ?bool $actif = null;

    #[ORM\ManyToOne(inversedBy: 'annees')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Diplome $diplome = null;

    #[ORM\OneToMany(targetEntity: Semestre::class, mappedBy: 'annee', orphanRemoval: true)]
    private Collection $semestres;

    #[ORM\OneToMany(targetEntity: ApcNiveau::class, mappedBy: 'annee')]
    private Collection $apcNiveaux;

    #[ORM\OneToMany(targetEntity: Bibliotheque::class, mappedBy: 'annee')]
    private Collection $bibliotheques;

    #[ORM\OneToMany(targetEntity: PortfolioUniv::class, mappedBy: 'annee')]
    private Collection $portfolioUnivs;

    public function __construct()
    {
        $this->semestres = new ArrayCollection();
        $this->apcNiveaux = new ArrayCollection();
        $this->bibliotheques = new ArrayCollection();
        $this->portfolioUnivs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    public function setSemestres(Collection $semestres): void
    {
        $this->semestres = $semestres;
    }

    public function setApcNiveaux(Collection $apcNiveaux): void
    {
        $this->apcNiveaux = $apcNiveaux;
    }

    public function setBibliotheques(Collection $bibliotheques): void
    {
        $this->bibliotheques = $bibliotheques;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getOrdre(): ?int
    {
        return $this->ordre;
    }

    public function setOrdre(int $ordre): static
    {
        $this->ordre = $ordre;

        return $this;
    }

    public function getLibelleLong(): ?string
    {
        return $this->libelle_long;
    }

    public function setLibelleLong(string $libelle_long): static
    {
        $this->libelle_long = $libelle_long;

        return $this;
    }

    public function isOptAlternance(): ?bool
    {
        return $this->opt_alternance;
    }

    public function setOptAlternance(bool $opt_alternance): static
    {
        $this->opt_alternance = $opt_alternance;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): static
    {
        $this->actif = $actif;

        return $this;
    }

    public function getDiplome(): ?Diplome
    {
        return $this->diplome;
    }

    public function setDiplome(?Diplome $diplome): static
    {
        $this->diplome = $diplome;

        return $this;
    }

    /**
     * @return Collection<int, Semestre>
     */
    public function getSemestres(): Collection
    {
        return $this->semestres;
    }

    public function addSemestre(Semestre $semestre): static
    {
        if (!$this->semestres->contains($semestre)) {
            $this->semestres->add($semestre);
            $semestre->setAnnee($this);
        }

        return $this;
    }

    public function removeSemestre(Semestre $semestre): static
    {
        if ($this->semestres->removeElement($semestre)) {
            // set the owning side to null (unless already changed)
            if ($semestre->getAnnee() === $this) {
                $semestre->setAnnee(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ApcNiveau>
     */
    public function getApcNiveaux(): Collection
    {
        return $this->apcNiveaux;
    }

    public function addApcNiveau(ApcNiveau $apcNiveau): static
    {
        if (!$this->apcNiveaux->contains($apcNiveau)) {
            $this->apcNiveaux->add($apcNiveau);
            $apcNiveau->setAnnee($this);
        }

        return $this;
    }

    public function removeApcNiveau(ApcNiveau $apcNiveau): static
    {
        if ($this->apcNiveaux->removeElement($apcNiveau)) {
            // set the owning side to null (unless already changed)
            if ($apcNiveau->getAnnee() === $this) {
                $apcNiveau->setAnnee(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Bibliotheque>
     */
    public function getBibliotheques(): Collection
    {
        return $this->bibliotheques;
    }

    public function addBibliotheque(Bibliotheque $bibliotheque): static
    {
        if (!$this->bibliotheques->contains($bibliotheque)) {
            $this->bibliotheques->add($bibliotheque);
            $bibliotheque->setAnnee($this);
        }

        return $this;
    }

    public function removeBibliotheque(Bibliotheque $bibliotheque): static
    {
        if ($this->bibliotheques->removeElement($bibliotheque)) {
            // set the owning side to null (unless already changed)
            if ($bibliotheque->getAnnee() === $this) {
                $bibliotheque->setAnnee(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PortfolioUniv>
     */
    public function getPortfolioUnivs(): Collection
    {
        return $this->portfolioUnivs;
    }

    public function addPortfolioUniv(PortfolioUniv $portfolioUniv): static
    {
        if (!$this->portfolioUnivs->contains($portfolioUniv)) {
            $this->portfolioUnivs->add($portfolioUniv);
            $portfolioUniv->setAnnee($this);
        }

        return $this;
    }

    public function removePortfolioUniv(PortfolioUniv $portfolioUniv): static
    {
        if ($this->portfolioUnivs->removeElement($portfolioUniv)) {
            // set the owning side to null (unless already changed)
            if ($portfolioUniv->getAnnee() === $this) {
                $portfolioUniv->setAnnee(null);
            }
        }

        return $this;
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: PageRepository::class)]
#[Broadcast]
class Page
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\ManyToOne(inversedBy: 'pages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?PortfolioUniv $portfolio = null;

    #[ORM\OneToMany(targetEntity: TracePage::class, mappedBy: 'page', orphanRemoval: true)]
    private Collection $tracePages;

    #[ORM\ManyToOne(inversedBy: 'pages')]
    private ?ApcNiveau $apc_niveau = null;

    #[ORM\ManyToOne(inversedBy: 'pages')]
    private ?ApcApprentissageCritique $apc_apprentissage_critique = null;

    /**
     * @var Collection<int, CritereApprentissageCritique>
     */
    #[ORM\OneToMany(targetEntity: CritereApprentissageCritique::class, mappedBy: 'page', orphanRemoval: true)]
    private Collection $critereApprentissageCritiques;

    /**
     * @var Collection<int, CritereNiveau>
     */
    #[ORM\OneToMany(targetEntity: CritereNiveau::class, mappedBy: 'page', orphanRemoval: true)]
    private Collection $critereNiveaux;

    public function __construct()
    {
        $this->tracePages = new ArrayCollection();
        $this->critereApprentissageCritiques = new ArrayCollection();
        $this->critereNiveaux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getPortfolio(): ?PortfolioUniv
    {
        return $this->portfolio;
    }

    public function setPortfolio(?PortfolioUniv $portfolio): static
    {
        $this->portfolio = $portfolio;

        return $this;
    }

    /**
     * @return Collection<int, TracePage>
     */
    public function getTracePages(): Collection
    {
        return $this->tracePages;
    }

    public function addTracePage(TracePage $tracePage): static
    {
        if (!$this->tracePages->contains($tracePage)) {
            $this->tracePages->add($tracePage);
            $tracePage->setPage($this);
        }

        return $this;
    }

    public function removeTracePage(TracePage $tracePage): static
    {
        if ($this->tracePages->removeElement($tracePage)) {
            // set the owning side to null (unless already changed)
            if ($tracePage->getPage() === $this) {
                $tracePage->setPage(null);
            }
        }

        return $this;
    }

    public function getApcNiveau(): ?ApcNiveau
    {
        return $this->apc_niveau;
    }

    public function setApcNiveau(?ApcNiveau $apc_niveau): static
    {
        $this->apc_niveau = $apc_niveau;

        return $this;
    }

    public function getApcApprentissageCritique(): ?ApcApprentissageCritique
    {
        return $this->apc_apprentissage_critique;
    }

    public function setApcApprentissageCritique(?ApcApprentissageCritique $apc_apprentissage_critique): static
    {
        $this->apc_apprentissage_critique = $apc_apprentissage_critique;

        return $this;
    }

    /**
     * @return Collection<int, CritereApprentissageCritique>
     */
    public function getCritereApprentissageCritiques(): Collection
    {
        return $this->critereApprentissageCritiques;
    }

    public function addCritereApprentissageCritique(CritereApprentissageCritique $critereApprentissageCritique): static
    {
        if (!$this->critereApprentissageCritiques->contains($critereApprentissageCritique)) {
            $this->critereApprentissageCritiques->add($critereApprentissageCritique);
            $critereApprentissageCritique->setPage($this);
        }

        return $this;
    }

    public function removeCritereApprentissageCritique(CritereApprentissageCritique $critereApprentissageCritique): static
    {
        if ($this->critereApprentissageCritiques->removeElement($critereApprentissageCritique)) {
            // set the owning side to null (unless already changed)
            if ($critereApprentissageCritique->getPage() === $this) {
                $critereApprentissageCritique->setPage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CritereNiveau>
     */
    public function getCritereNiveaux(): Collection
    {
        return $this->critereNiveaux;
    }

    public function addCritereNiveau(CritereNiveau $critereNiveau): static
    {
        if (!$this->critereNiveaux->contains($critereNiveau)) {
            $this->critereNiveaux->add($critereNiveau);
            $critereNiveau->setPage($this);
        }

        return $this;
    }

    public function removeCritereNiveau(CritereNiveau $critereNiveau): static
    {
        if ($this->critereNiveaux->removeElement($critereNiveau)) {
            // set the owning side to null (unless already changed)
            if ($critereNiveau->getPage() === $this) {
                $critereNiveau->setPage(null);
            }
        }

        return $this;
    }
}

src/Form/PortfolioUnivType.php
<?php

namespace App\Form;

use App\Entity\Annee;
use App\Entity\Etudiant;
use App\Entity\PortfolioUniv;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\UX\Dropzone\Form\DropzoneType;

class PortfolioUnivType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir un titre',
                    ]),
                    new Length([
                        'max' => 100,
                        'maxMessage' => 'Le titre ne peut pas dépasser {{ limit }} caractères',
                    ]),
                ],
                'label' => 'Titre',
                'label_attr' => [
                    'class' => 'form-label'
                ],
                'attr' => [
                    'class' => "form-control",
                    'placeholder' => 'Titre du portfolio',
                ],
                'help' => '100 caractères maximum',
                'required' => true,
            ])
            ->add('banniere', DropzoneType::class, [
                'label' => 'Bannière',
                'label_attr' => [
                    'class' => 'form-label'
                ],
                'attr' => [
                    'class' => "form-control banner-dropzone",
                ],
                'help' => 'Image de couverture du portfolio',
                'required' => false,
                'mapped' => false,
            ])
            ->add('description', TextareaType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir votre description',
                    ]),
                ],
                'label' => 'Description',
                'label_attr' => ['class' => 'form-label'],
                'attr' => ['class' => 'form-control', 'placeholder' => 'Mon portfolio universitaire regroupe l\'ensemble de mes travaux, tous liés par l\'intermédiaire des compétences universitaires de ma formation.', 'rows' => 3, 'id' => 'trace_abstract_description'],
                'help' => 'Un court paragraphe d\'introduction à votre portfolio',
                'mapped' => true,
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PortfolioUniv::class,
        ]);
    }
}

templates/portfolio_univ/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}UniFolio - Portfolio Universitaire{% endblock %}

    {% block header %}
    {% endblock %}

{% block main %}
    {% import 'macros/breadcrumbs.twig' as breadcrumb_macros %}
    {{ breadcrumb_macros.breadcrumbs([
        {'name': 'Accueil', 'url': '/'},
        {'name': 'Dashboard', 'url': '/etudiant/dashboard'},
        {'name': 'Bibliothèque de portfolios universitaires', 'url': '/etudiant/portfolioUniv'},
        {'name': 'Edition d\'un portfolio universitaire', 'url': null}
    ]) }}

    <section class="container-custom min-vh-100 section-pt">
        <div class="row d-flex">
            <article class="col-lg-8 col-12">
                <div class="card p-5">
                    <div class="card-header">
                        <h2>Edition d'un portfolio universitaire</h2>
                    </div>
                    <div class="card-body">
                        <turbo-frame id="portfolio-form">
                            {{ include('portfolio_univ/step/_'~step~'.html.twig') }}
                        </turbo-frame>
                    </div>
                </div>
            </article>
            <aside class="col-lg-4 col-12">
                <div class="card p-5 h-100">
                    <div class="card-header">
                        <h2>Guide du portfolio</h2>
                        <em>Le portfolio universitaire est un outil qui permet de présenter de manière organisée et
                            structurée les projets réalisés, les centres d’intérêt, les activités extra-universitaires,
                            dans une démarche de réflexion sur son parcours et de valorisation de ses compétences.</em>
                        <hr>
                    </div>
                    <div class="card-body">
                        <h4>Etapes</h4>
                        <ul class="progress-list">
                            <li>Initialisation du portfolio</li>
                            <li>Création d'une ou plusieurs pages</li>
                            <li>Création ou ajout de traces dans les pages</li>
                            <li>Création ou ajout d'un CV <small class="text-muted">- Facultatif</small></li>
                        </ul>

                        <h4>Auto-évaluation</h4>
                        <em>Dans le cadre de notre engagement envers l'autonomie et le développement des compétences, vous allez évaluer vos propres travaux selon des critères pré-établis.</em>

                        <ul class="card-list">
                            <li><strong>Prenez du recul :</strong> Quels étaient vos objectifs ? Dans quelle mesure pensez-vous les avoir atteints ?</li>

                            <li><strong>Evaluez vos productions :</strong> Identifiez vos forces, vos faiblesses et vos axes d'amélioration.</li>

                            <li><strong>Trouvez des solutions :</strong> Quelles actions pouvez-vous entreprendre pour renforcer vos compétences dans ces domaines ?</li>

                            <li><strong>Partagez votre ressenti :</strong> Vos évaluations offriront aux enseignants un regard nouveau sur votre travail.</li>
                        </ul>
                    </div>
                </div>
            </aside>
        </div>
    </section>
{% endblock %}

templates/portfolio_univ/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}UniFolio - Portfolio Universitaire{% endblock %}

    {% block header %}
    {% endblock %}

{% block main %}
    {% import 'macros/breadcrumbs.twig' as breadcrumb_macros %}
    {{ breadcrumb_macros.breadcrumbs([
        {'name': 'Accueil', 'url': '/'},
        {'name': 'Dashboard', 'url': '/etudiant/dashboard'},
        {'name': 'Bibliothèque de portfolios universitaires', 'url': '/etudiant/portfolioUniv'},
        {'name': 'Nouveau portfolio universitaire', 'url': null}
    ]) }}

    <section class="container-custom min-vh-100 section-pt">
        <div class="row d-flex">
            <article class="col-lg-8 col-12">
                <div class="card p-5">
                    <div class="card-header">
                        <h2>Création d'un portfolio universitaire</h2>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            {{ form_start(form) }}
                            <div class="col-12 p-2">
                                {{ form_row(form.libelle) }}
                            </div>
                            <div class="col-12 p-2">
                                <div class="alert alert-warning">
                                    <span>Si vous n'ajoutez pas de bannière, une image par défaut sera utilisée. S'il y en a déjà une, pas besoin d'en ajouter une nouvelle.</span>
                                </div>
                                {{ form_row(form.banniere) }}
                            </div>
                            <div class="col-12 p-2">
                                {{ form_row(form.description) }}
                            </div>
                            <hr>
                            <button type="submit" class="btn btn-primary-color text-uppercase">Enregistrer et passer à
                                l'étape suivante
                            </button>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </article>
            <aside class="col-lg-4 col-12">
                <div class="card p-5 h-100">
                    <div class="card-header">
                        <h2>Guide du portfolio</h2>
                        <em>Le portfolio universitaire est un outil qui permet de présenter de manière organisée et
                            structurée les projets réalisés, les centres d’intérêt, les activités extra-universitaires,
                            dans une démarche de réflexion sur son parcours et de valorisation de ses compétences.</em>
                        <hr>
                    </div>
                    <div class="card-body">
                        <h4>Etapes</h4>
                        <ul class="progress-list">
                            <li>Initialisation du portfolio</li>
                            <li>Création d'une ou plusieurs pages</li>
                            <li>Création ou ajout de traces dans les pages</li>
                            <li>Création ou ajout d'un CV <small class="text-muted">- Facultatif</small></li>
                        </ul>
                    </div>
                </div>
            </aside>
        </div>
    </section>
{% endblock %}

templates/portfolio_univ/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UniFolio - Portfolios universitaires{% endblock %}

    {% block header %}
    {% endblock %}

{% block main %}
    {% import 'macros/breadcrumbs.twig' as breadcrumb_macros %}
    {{ breadcrumb_macros.breadcrumbs([
        {'name': 'Accueil', 'url': '/'},
        {'name': 'Dashboard', 'url': '/etudiant/dashboard'},
        {'name': 'Bibliothèque de portfolios universitaires', 'url': null}
    ]) }}

    <section class="container-custom min-vh-100 section-pt">
        <div class="row">
            <article>
                <div class="card p-5">
                    <twig:AllPortfolios/>
                </div>
            </article>
        </div>
    </section>
{% endblock %}

templates/portfolio_univ/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UniFolio - Dashboard{% endblock %}

    {% block header %}
    {% endblock %}

{% block main %}
    {% import 'macros/breadcrumbs.twig' as breadcrumb_macros %}
    {{ breadcrumb_macros.breadcrumbs([
        {'name': 'Accueil', 'url': '/'},
        {'name': 'Dashboard', 'url': '/etudiant/dashboard'},
        {'name': 'Bibliothèque de portfolios universitaires', 'url': '/etudiant/portfolioUniv'},
        {'name': 'Portfolio' , 'url': null}
    ]) }}


    <section class="container-custom min-vh-100 section-pt">
        <article>
            <div class="card p-0 h-100">
                <div class="portfolio-banner" style="background-image: url({{ portfolio.banniere }})"></div>
                <div class="card-header p-5 m-5 mt-0 mb-0 text-center">
                    <h2 class="text-center">{{ portfolio.libelle }}</h2>
                    <p class="text-muted">{{ portfolio.annee.libelleLong }}</p>
                    <p>{{ portfolio.etudiant.prenom }} {{ portfolio.etudiant.nom }}
                        - {{ portfolio.etudiant.semestre.libelle }} - {% for g in portfolio.etudiant.groupe %}
                            {% if 'TP' in g.typeGroupe.libelle %}
                                Groupe {{ g.libelle }}
                            {% endif %}
                        {% endfor %}</p>
                </div>

                <div class="card-body p-5 m-5 border">

                    {% for page in pages.currentPageResults %}
                        <h2 class="pill-competence m-auto mb-5 {{ page.apcNiveau.apcCompetence.couleur ?? page.apcApprentissageCritique.apcNiveau.apcCompetence.couleur }}">{{ page.libelle }}</h2>

                        {% if tracesPage is empty %}
                            <div class="alert alert-warning w-100">Aucune trace pour le moment</div>
                        {% else %}

                            {% for trace in tracesPage %}
                                <twig:TraceContent id="{{ trace.id }}"/>
                            {% endfor %}
                        {% endif %}

                        <div>
                            <h4>Validation de la compétence {{ page.libelle }}</h4>

                            <table>
                                <thead>
                                <tr>
                                    <th>
                                        Critère
                                    </th>
                                    <th>
                                        Resultat
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for critereCompetence in criteresCompetences %}
                                    <tr>
                                        <td>
                                            {{ critereCompetence.critere.libelle }}
                                        </td>
                                        <td>
                                            {% if critereCompetence.valeur is null %}
                                                <span class="text-muted">En attente</span>
                                            {% else %}
                                                {{ critereCompetence.valeur }}
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% endfor %}

                    <div class=" navigation text-end">
                        {% if pages.hasPreviousPage %}
                            <a href="{{ path('app_portfolio_univ_show', {'id': portfolio.id, 'page': pages.previousPage}) }}"
                               class="m-2">Page précédente</a>
                        {% endif %}

                        <span class="m-2">{{ pages.currentPage }}</span>
                        {% if pages.nbPages > 1 %}
                            <span class="m-2">/</span>
                            <a href="{{ path('app_portfolio_univ_show', {'id': portfolio.id, 'page': pages.nbPages}) }}"
                               class="m-2">{{ pages.nbPages }}</a>
                        {% endif %}

                        {% if pages.hasNextPage %}
                            <a href="{{ path('app_portfolio_univ_show', {'id': portfolio.id, 'page': pages.nextPage}) }}"
                               class="m-2">Page suivante</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </article>
    </section>
{% endblock %}