src/Entity/Cv.php
<?php

namespace App\Entity;

use App\Repository\CvRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CvRepository::class)]
class Cv
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_modification = null;

    #[ORM\Column(length: 100)]
    private ?string $intitule = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?array $langues = null;

    #[ORM\Column(nullable: true)]
    private ?array $soft_skills = null;

    #[ORM\Column(nullable: true)]
    private ?array $hard_skills = null;

    #[ORM\Column(nullable: true)]
    private ?array $reseaux = null;

    #[ORM\OneToMany(targetEntity: Experience::class, mappedBy: 'cv')]
    private Collection $experiences;

    #[ORM\OneToMany(targetEntity: Formation::class, mappedBy: 'cv')]
    private Collection $formations;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    public function __construct()
    {
        $this->experiences = new ArrayCollection();
        $this->formations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->date_modification;
    }

    public function setDateModification(?\DateTimeInterface $date_modification): static
    {
        $this->date_modification = $date_modification;

        return $this;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): static
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLangues(): ?array
    {
        return $this->langues;
    }

    public function setLangues(?array $langues): static
    {
        $this->langues = $langues;

        return $this;
    }

    public function getSoftSkills(): ?array
    {
        return $this->soft_skills;
    }

    public function setSoftSkills(?array $soft_skills): static
    {
        $this->soft_skills = $soft_skills;

        return $this;
    }

    public function getHardSkills(): ?array
    {
        return $this->hard_skills;
    }

    public function setHardSkills(?array $hard_skills): static
    {
        $this->hard_skills = $hard_skills;

        return $this;
    }

    public function getReseaux(): ?array
    {
        return $this->reseaux;
    }

    public function setReseaux(?array $reseaux): static
    {
        $this->reseaux = $reseaux;

        return $this;
    }

    /**
     * @return Collection<int, Experience>
     */
    public function getExperiences(): Collection
    {
        return $this->experiences;
    }

    public function addExperience(Experience $experience): static
    {
        if (!$this->experiences->contains($experience)) {
            $this->experiences->add($experience);
            $experience->setCv($this);
        }

        return $this;
    }

    public function removeExperience(Experience $experience): static
    {
        if ($this->experiences->removeElement($experience)) {
            // set the owning side to null (unless already changed)
            if ($experience->getCv() === $this) {
                $experience->setCv(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Formation>
     */
    public function getFormations(): Collection
    {
        return $this->formations;
    }

    public function addFormation(Formation $formation): static
    {
        if (!$this->formations->contains($formation)) {
            $this->formations->add($formation);
            $formation->setCv($this);
        }

        return $this;
    }

    public function removeFormation(Formation $formation): static
    {
        if ($this->formations->removeElement($formation)) {
            // set the owning side to null (unless already changed)
            if ($formation->getCv() === $this) {
                $formation->setCv(null);
            }
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: PageRepository::class)]
#[Broadcast]
class Page
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\ManyToOne(inversedBy: 'pages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?PortfolioUniv $portfolio = null;

    #[ORM\OneToMany(targetEntity: TracePage::class, mappedBy: 'page', orphanRemoval: true)]
    private Collection $tracePages;

    #[ORM\ManyToOne(inversedBy: 'pages')]
    private ?ApcNiveau $apc_niveau = null;

    #[ORM\ManyToOne(inversedBy: 'pages')]
    private ?ApcApprentissageCritique $apc_apprentissage_critique = null;

    /**
     * @var Collection<int, CritereApprentissageCritique>
     */
    #[ORM\OneToMany(targetEntity: CritereApprentissageCritique::class, mappedBy: 'page', orphanRemoval: true)]
    private Collection $critereApprentissageCritiques;

    /**
     * @var Collection<int, CritereNiveau>
     */
    #[ORM\OneToMany(targetEntity: CritereNiveau::class, mappedBy: 'page', orphanRemoval: true)]
    private Collection $critereNiveaux;

    public function __construct()
    {
        $this->tracePages = new ArrayCollection();
        $this->critereApprentissageCritiques = new ArrayCollection();
        $this->critereNiveaux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getPortfolio(): ?PortfolioUniv
    {
        return $this->portfolio;
    }

    public function setPortfolio(?PortfolioUniv $portfolio): static
    {
        $this->portfolio = $portfolio;

        return $this;
    }

    /**
     * @return Collection<int, TracePage>
     */
    public function getTracePages(): Collection
    {
        return $this->tracePages;
    }

    public function addTracePage(TracePage $tracePage): static
    {
        if (!$this->tracePages->contains($tracePage)) {
            $this->tracePages->add($tracePage);
            $tracePage->setPage($this);
        }

        return $this;
    }

    public function removeTracePage(TracePage $tracePage): static
    {
        if ($this->tracePages->removeElement($tracePage)) {
            // set the owning side to null (unless already changed)
            if ($tracePage->getPage() === $this) {
                $tracePage->setPage(null);
            }
        }

        return $this;
    }

    public function getApcNiveau(): ?ApcNiveau
    {
        return $this->apc_niveau;
    }

    public function setApcNiveau(?ApcNiveau $apc_niveau): static
    {
        $this->apc_niveau = $apc_niveau;

        return $this;
    }

    public function getApcApprentissageCritique(): ?ApcApprentissageCritique
    {
        return $this->apc_apprentissage_critique;
    }

    public function setApcApprentissageCritique(?ApcApprentissageCritique $apc_apprentissage_critique): static
    {
        $this->apc_apprentissage_critique = $apc_apprentissage_critique;

        return $this;
    }

    /**
     * @return Collection<int, CritereApprentissageCritique>
     */
    public function getCritereApprentissageCritiques(): Collection
    {
        return $this->critereApprentissageCritiques;
    }

    public function addCritereApprentissageCritique(CritereApprentissageCritique $critereApprentissageCritique): static
    {
        if (!$this->critereApprentissageCritiques->contains($critereApprentissageCritique)) {
            $this->critereApprentissageCritiques->add($critereApprentissageCritique);
            $critereApprentissageCritique->setPage($this);
        }

        return $this;
    }

    public function removeCritereApprentissageCritique(CritereApprentissageCritique $critereApprentissageCritique): static
    {
        if ($this->critereApprentissageCritiques->removeElement($critereApprentissageCritique)) {
            // set the owning side to null (unless already changed)
            if ($critereApprentissageCritique->getPage() === $this) {
                $critereApprentissageCritique->setPage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CritereNiveau>
     */
    public function getCritereNiveaux(): Collection
    {
        return $this->critereNiveaux;
    }

    public function addCritereNiveau(CritereNiveau $critereNiveau): static
    {
        if (!$this->critereNiveaux->contains($critereNiveau)) {
            $this->critereNiveaux->add($critereNiveau);
            $critereNiveau->setPage($this);
        }

        return $this;
    }

    public function removeCritereNiveau(CritereNiveau $critereNiveau): static
    {
        if ($this->critereNiveaux->removeElement($critereNiveau)) {
            // set the owning side to null (unless already changed)
            if ($critereNiveau->getPage() === $this) {
                $critereNiveau->setPage(null);
            }
        }

        return $this;
    }
}

src/Entity/Trace.php
<?php

namespace App\Entity;

use App\Repository\TraceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: TraceRepository::class)]
#[Broadcast]
class Trace
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'traces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Bibliotheque $bibliotheque = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_modification = null;

    #[ORM\Column(length: 255,nullable: true)]
    private ?string $type = null;

    #[ORM\Column(length: 100)]
    private ?string $libelle = null;

    #[ORM\Column(nullable: true)]
    private array $contenu = [];

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $legende = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_realisation = null;

    #[ORM\Column(length: 255)]
    private ?string $contexte = null;

    #[ORM\OneToMany(targetEntity: TracePage::class, mappedBy: 'trace', orphanRemoval: true)]
    private Collection $tracePages;

    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'trace')]
    private Collection $commentaires;

    /**
     * @var Collection<int, TraceCompetence>
     */
    #[ORM\OneToMany(targetEntity: TraceCompetence::class, mappedBy: 'trace', cascade: ['persist'], orphanRemoval: true)]
    private Collection $traceCompetences;

    public function __construct()
    {
        $this->tracePages = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->traceCompetences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBibliotheque(): ?Bibliotheque
    {
        return $this->bibliotheque;
    }

    public function setBibliotheque(?Bibliotheque $bibliotheque): static
    {
        $this->bibliotheque = $bibliotheque;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->date_modification;
    }

    public function setDateModification(?\DateTimeInterface $date_modification): static
    {
        $this->date_modification = $date_modification;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getContenu(): array
    {
        return $this->contenu;
    }

    public function setContenu(?array $contenu): static
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLegende(): ?string
    {
        return $this->legende;
    }

    public function setLegende(?string $legende): static
    {
        $this->legende = $legende;

        return $this;
    }

    public function getDateRealisation(): ?\DateTimeInterface
    {
        return $this->date_realisation;
    }

    public function setDateRealisation(?\DateTimeInterface $date_realisation): static
    {
        $this->date_realisation = $date_realisation;

        return $this;
    }

    public function getContexte(): ?string
    {
        return $this->contexte;
    }

    public function setContexte(?string $contexte): static
    {
        $this->contexte = $contexte;

        return $this;
    }

    /**
     * @return Collection<int, TracePage>
     */
    public function getTracePages(): Collection
    {
        return $this->tracePages;
    }

    public function addTracePage(TracePage $tracePage): static
    {
        if (!$this->tracePages->contains($tracePage)) {
            $this->tracePages->add($tracePage);
            $tracePage->setTrace($this);
        }

        return $this;
    }

    public function removeTracePage(TracePage $tracePage): static
    {
        if ($this->tracePages->removeElement($tracePage)) {
            // set the owning side to null (unless already changed)
            if ($tracePage->getTrace() === $this) {
                $tracePage->setTrace(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setTrace($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getTrace() === $this) {
                $commentaire->setTrace(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, TraceCompetence>
     */
    public function getTraceCompetences(): Collection
    {
        return $this->traceCompetences;
    }

    public function addTraceCompetence(TraceCompetence $traceCompetence): static
    {
        if (!$this->traceCompetences->contains($traceCompetence)) {
            $this->traceCompetences->add($traceCompetence);
            $traceCompetence->setTrace($this);
        }

        return $this;
    }

    public function removeTraceCompetence(TraceCompetence $traceCompetence): static
    {
        if ($this->traceCompetences->removeElement($traceCompetence)) {
            // set the owning side to null (unless already changed)
            if ($traceCompetence->getTrace() === $this) {
                $traceCompetence->setTrace(null);
            }
        }

        return $this;
    }
}

templates/components/RetourPedagogiqueCard.html.twig
<div{{ attributes }}>
    <!-- component html -->
</div>

templates/components/TraceBiblioCard.html.twig
<div{{ attributes }}>
{#    {% set totalValidations = this.trace.validations|length %}#}
{#    {% set validated = 0 %}#}

{#    {% for validation in this.trace.validations %}#}
{#        {% if validation.etat == 3 %}#}
{#            {% set validated = validated + 1 %}#}
{#        {% endif %}#}
{#    {% endfor %}#}

{#    {% set percentage = 0 %}#}
{#    {% if totalValidations != 0 %}#}
{#        {% set percentage = (validated/totalValidations)*100 %}#}
{#    {% endif %}#}

    <tr>
        <td>
            <input type="checkbox" class="form-check-input"
                   data-model="selectedTraces[]"
                   value="{{ this.trace.id }}"/>
        </td>
        <td>
            <div class="d-flex flex-column gap-1">
                <div class="pill">
                    {% if this.type is null %}
                        Type non défini
                    {% else %}
                        {{ this.trace.contenu|length }}
                        {{ this.type }}{% if this.trace.contenu|length > 1 %}s{% endif %}
                    {% endif %}
                </div>
                <p class="table-primary-text">{{ this.trace.libelle }}</p>
            </div>
        </td>
        <td>
            {{ this.trace.dateModification|date('d/m/Y') }}
        </td>
        <td>
            {{ this.trace.bibliotheque.annee.libelle }}
        </td>
        <td class="d-flex flex-column gap-1 h-100">
            {% if this.trace.traceCompetences is empty %}
                <div class="pill-danger d-flex align-items-center gap-1">
                    <twig:ux:icon name="bi:exclamation-octagon" width="15" height="15"/>
                    Aucune compétence liée
                </div>
            {% else %}
                {% for traceCompetences in this.trace.traceCompetences %}
                    <div class="pill-competence w-100 {{ traceCompetences.apcNiveau.apcCompetence.couleur ?? traceCompetences.apcApprentissageCritique.apcNiveau.apcCompetence.couleur }}">
                        {{ traceCompetences.apcNiveau.apcCompetence.nomCourt ?? traceCompetences.apcApprentissageCritique.libelle }}
                    </div>
                {% endfor %}
            {% endif %}
        </td>
        <td>
            {% if this.trace.traceCompetences is empty or this.trace.contenu is empty or this.trace.contenu is null or this.trace.description is empty or this.trace.description is null or this.trace.contexte is empty or this.trace.contexte is null %}
                <div class="pill-danger d-flex align-items-center gap-1 dropdown-toggle" data-bs-toggle="dropdown"
                     aria-expanded="false" style="cursor: pointer">
                    <twig:ux:icon name="bi:exclamation-triangle-fill" width="15px" height="auto"/>
                    Trace incomplète
                    <ul class="dropdown-menu p-3">
                        {% if this.trace.traceCompetences is empty %}
                            <li class="text-danger mb-2 mt-2">
                                Aucune compétence liée
                            </li>

                        {% endif %}
                        {% if this.trace.contenu is empty or this.trace.contenu is null %}
                            <li class="text-danger mb-2 mt-2">
                                Aucun média d'illustration
                            </li>

                        {% endif %}
                        {% if this.trace.description is empty or this.trace.description is null %}
                            <li class="text-danger mb-2 mt-2">
                                Aucun argumentaire
                            </li>

                        {% endif %}
                        {% if this.trace.contexte is empty or this.trace.contexte is null %}
                            <li class="text-danger mb-2 mt-2">
                                Pas de contexte renseigné
                            </li>

                        {% endif %}
                    </ul>
                </div>
            {% else %}
                <div class="pill-success d-flex align-items-center gap-1">
                    Trace complète
                    <twig:ux:icon name="bi:check-circle-fill" width="15" height="15"/>
                </div>
            {% endif %}
        </td>
        <td>
            <div class="d-flex gap-2">
                <a href="{{ path('app_trace_show', {'id': this.trace.id}) }}">
                    <button class="btn-info d-flex justify-content-center align-items-center">
                        <twig:ux:icon name="bi:eye-fill" width="15" height="15"/>
                    </button>
                </a>
                <a href="{{ path('app_trace_edit', {'id': this.trace.id}) }}">
                    <button class="btn-warning d-flex justify-content-center align-items-center">
                        <twig:ux:icon name="bi:pencil-square" width="15" height="15"/>
                    </button>
                </a>
                <button class="btn-danger d-flex justify-content-center align-items-center" data-bs-toggle="modal"
                        data-bs-target="#delete{{ this.trace.id }}Modal">
                    <twig:ux:icon name="bi:x-square-fill" width="15" height="15"/>
                </button>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="delete{{ this.trace.id }}Modal" tabindex="-1"
                 aria-labelledby="delete{{ this.trace.id }}ModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="delete{{ this.trace.id }}ModalLabel">Supprimer une
                                trace</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body d-flex flex-column align-items-center gap-4">
                            <twig:ux:icon name="bi:exclamation-octagon" width="50" height="auto" color="red"/>
                            <p class="text-danger">Attention, cette action est irréversible !</p>

                            <p>
                                La trace "{{ this.trace.libelle }}" va être supprimée. Êtes-vous sûr de vouloir
                                continuer ?
                            </p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                            <a href="{{ path('app_trace_delete', {'id': this.trace.id}) }}">
                                <button type="button" class="btn btn-primary">Confirmer</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
</div>

templates/components/TraceContent.html.twig
<div{{ attributes }}>
    <h2 class="mb-2">{{ this.trace.libelle }}</h2>

    <div class="card-infos-min border-bottom d-flex flex-column gap-2">
        <p class="m-0">Publiée le : {{ this.trace.dateCreation|date("d/m/Y") }}
            {% if this.trace.type is null %}
            &nbsp;|&nbsp;
        <p class="text-danger m-0">Aucun média associé à cette trace</p>
        {% else %}
            &nbsp;|&nbsp;
            {{ this.trace.contenu|length }}
            {{ this.traceType|lower }}{% if this.trace.contenu|length > 1 %}s{% endif %}
        {% endif %}
        </p>
        <div class="d-flex flex-row gap-4 align-items-center mb-4">
            <p class="text-muted m-0">
                Date de réalisation : {{ this.trace.dateRealisation|date("m/Y") }}
            </p>
            <div class="pill">
                {{ this.trace.contexte }}
            </div>
            {% if this.trace.traceCompetences is empty %}
                <div class="pill-danger d-flex align-items-center gap-1">
                    <twig:ux:icon name="bi:exclamation-octagon" width="15" height="15"/>
                    Aucune compétence liée
                </div>
            {% else %}
                {% for traceCompetences in this.trace.traceCompetences %}
                    {% if traceCompetences.apcNiveau and traceCompetences.apcNiveau.actif == true %}
                        <div class="pill-competence {{ traceCompetences.apcNiveau.apcCompetence.couleur }}">
                            {{ traceCompetences.apcNiveau.apcCompetence.nomCourt }}
                        </div>
                    {% else %}
                        <div class="pill-competence {{ traceCompetences.apcApprentissageCritique.apcNiveau.apcCompetence.couleur }}">
                            {{ traceCompetences.apcApprentissageCritique.libelle }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="card-body">
        {% if this.trace.contenu is not null and this.trace.contenu is not empty %}
            <div class="row d-flex justify-content-center mb-5 mt-5">
                {% include('/partials/trace/_' ~ constant('TYPE', this.typeTrace(this.type)) ~ '_content.html.twig') %}
                <p class="text-muted m-0 mt-2">
                    {{ this.trace.legende }}
                </p>
            </div>

        {% else %}
            <div class="alert alert-warning text-center" role="alert">
                Aucun média associé à cette trace
            </div>
        {% endif %}

        <hr>

        <div class="row justify-content-center">
            <div class="col-lg-11 col-12 mt-4 mb-4">
                {% if this.trace.description is not null and this.trace.description is not empty %}
                    {{ this.trace.description|raw }}
                {% else %}
                    <p class="text-danger">Aucun argumentaire pour cette trace</p>
                {% endif %}
            </div>
        </div>

        <hr>


        <div class="row justify-content-center">

            <div class="mt-4 mb-4">
                <h4>Commentaires</h4>
                {% set visibleComments = this.trace.commentaires|filter(commentaire => commentaire.visibilite == 1) %}
                {% if visibleComments is empty %}
                    <p>Aucun commentaire pour le moment</p>
                {% else %}
                    {% for commentaire in this.trace.commentaires %}
                        {% if commentaire.visibilite == 1 %}
                            <div class="card"
                                 style="margin-bottom: 10px; box-shadow: none; border: 1px solid lightgrey">
                                <div class="card-header">
                                    <div style="display: flex; justify-content: space-between; align-items: center">
                                        <h6 class="card-subtitle">{{ commentaire.enseignant.prenom }} {{ commentaire.enseignant.nom }}</h6>
                                        <small>
                                            {{ commentaire.datecreation|date('d-m-Y H:i') }}
                                        </small>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <p class="card-text">{{ commentaire.contenu }}</p>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/components/TracePortfolioPreview.html.twig
<div{{ attributes }}>
    <div class="row g-3 d-flex flex-row align-items-center flex-wrap">

        <div class="col-lg-3 col-12">
            {% if this.type is not null %}
            {% include('/partials/trace/_'~this.type~'_preview.html.twig') %}
            {% endif %}
        </div>

        <div class="col-lg-9 col-12 d-flex flex-column align-items-start justify-content-start">
            <h5>{{ this.trace.libelle }}</h5>
            <small class="text-muted">Publiée le : {{ this.trace.dateCreation|date('d-m-Y') }}
                -
                {{ this.trace.contenu|length }}
                {{ this.type }}{% if this.trace.contenu|length > 1 %}s{% endif %}</small>
            {% for traceCompetence in this.trace.traceCompetences %}
                {% if traceCompetence.apcNiveau and traceCompetence.apcNiveau.actif == true %}
                    <small class="{{ traceCompetence.apcNiveau.apcCompetence.couleur }}txt ue mb-2">{{ traceCompetence.apcNiveau.apcCompetence.nomCourt }}
                        • {{ traceCompetence.apcNiveau.libelle }}
                    </small>
                {% else %}
                    <small class="{{ traceCompetence.apcApprentissageCritique.apcNiveau.apcCompetence.couleur }}txt ue mb-2">{{ traceCompetence.apcApprentissageCritique.code }}
                        | {{ traceCompetence.apcApprentissageCritique.libelle }}
                    </small>
                {% endif %}
            {% endfor %}
            <p>{{ this.trace.description|striptags|slice(0, 300)|raw }}...</p>
        </div>
    </div>
</div>